name: bookmark
description: A AI assistant for your bookmarks
publish_to: 'none'
version: 1.0.0+1
# Major.Minor.Patch+Build
# MAJOR – Breaking changes (e.g., API redesign).
# MINOR – Backward-compatible features (e.g., new screens or components).
# PATCH – Bug fixes or small changes.

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  injectable: ^2.4.4
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  logger: ^2.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_markdown: ^0.7.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/gilroy/Gilroy-Black.ttf
        - asset: fonts/gilroy/Gilroy-Heavy.ttf
        - asset: fonts/gilroy/Gilroy-ExtraBold.ttf
        - asset: fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: fonts/gilroy/Gilroy-Bold.ttf
        - asset: fonts/gilroy/Gilroy-Medium.ttf
        - asset: fonts/gilroy/Gilroy-Regular.ttf
        - asset: fonts/gilroy/Gilroy-Light.ttf
        - asset: fonts/gilroy/Gilroy-Thin.ttf
